---
postgresql:
  adapter: postgresql
  database: persistent_enum_test
mysql2:
  adapter: mysql2
  database: persistent_enum_test
  host: <%= ENV.fetch('MYSQL_HOST') { '127.0.0.1' } %>
  user: <%= ENV.fetch('MYSQL_USER') { 'root' } %>
sqlite3:
  adapter: sqlite3
  database: ":memory:"
