dist: trusty
sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4
  - 2.5
gemfile:
  - gemfiles/rails_5_0.gemfile
  - gemfiles/rails_5_1.gemfile
env:
  - TEST_DATABASE_ENVIRONMENT=postgresql
  - TEST_DATABASE_ENVIRONMENT=mysql2
  - TEST_DATABASE_ENVIRONMENT=sqlite3
services:
  - postgresql
  - mysql
before_install:
  # Travis' Ruby 2.5.0 ships broken rubygems, won't run rake.
  # Workaround: update rubygems. See travis-ci issue 8978
  - gem install bundler
before_script:
  - psql -c 'CREATE DATABASE persistent_enum_test;' -U postgres
  - mysql -e 'CREATE DATABASE persistent_enum_test;'
addons:
  postgresql: "9.6"
notifications:
  email: false
