dist: trusty
sudo: false
language: ruby
cache: bundler

rvm:
  - 2.4
  - 2.5
  - 2.6

gemfile:
  - gemfiles/rails_5_1.gemfile
  - gemfiles/rails_5_2.gemfile

services:
  - mysql

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
      - postgresql-server-dev-10
env:
  global:
    - PGPORT=5433
  matrix:
    - TEST_DATABASE_ENVIRONMENT=postgresql
    - TEST_DATABASE_ENVIRONMENT=mysql2
    - TEST_DATABASE_ENVIRONMENT=sqlite3

before_install:
  # Travis' Ruby 2.5.0 ships broken rubygems, won't run rake.
  # Workaround: update rubygems. See travis-ci issue 8978
  - gem install bundler
before_script:
  - psql -c 'CREATE DATABASE persistent_enum_test;'
  - mysql -e 'CREATE DATABASE persistent_enum_test;'

notifications:
  email: false
