version: 2.1

executors:
  ruby-sqlite: &ruby
    parameters: &ruby_params
      ruby-version:
        type: string
        default: "2.7"
      gemfile:
        type: string
        default: "Gemfile"
    environment:
      TEST_DATABASE_ENVIRONMENT: sqlite3
    docker:
      - &ruby_docker_ruby
        image: circleci/ruby:<< parameters.ruby-version >>
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
          BUNDLE_GEMFILE: << parameters.gemfile >>
  ruby-pg:
    <<: *ruby
    parameters:
      <<: *ruby_params
      pg-version:
        type: string
        default: "12"
    environment:
      TEST_DATABASE_ENVIRONMENT: postgresql
      PGHOST: 127.0.0.1
      PGUSER: eikaiwa
    docker:
      - *ruby_docker_ruby
      - image: circleci/postgres:<< parameters.pg-version >>-alpine
        environment:
          POSTGRES_USER: eikaiwa
          POSTGRES_DB: persistent_enum_test
          POSTGRES_PASSWORD: ""
  ruby-mysql:
    <<: *ruby
    parameters:
      <<: *ruby_params
      mysql-version:
        type: string
        default: "5.7"
    environment:
      TEST_DATABASE_ENVIRONMENT: mysql2
      MYSQL_HOST: 127.0.0.1
      MYSQL_USER: root
    docker:
      - *ruby_docker_ruby
      - image: circleci/mysql:<< parameters.mysql-version >>
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: persistent_enum_test

jobs:
  test:
    parameters:
      executor-name:
        type: string
      ruby-version:
        type: string
      gemfile:
        type: string
      database-steps:
        type: steps
        default: []
    executor:
      name: << parameters.executor-name >>
      ruby-version: << parameters.ruby-version >>
      gemfile: << parameters.gemfile >>
    parallelism: 1
    steps:
      - checkout

      - run:
          # Remove the non-appraisal gemfile for safety: we never want to use it.
          name: Prepare bundler
          command: bundle -v && rm Gemfile

      - run:
          name: Compute a gemfile lock
          command: bundle lock && cp "${BUNDLE_GEMFILE}.lock" /tmp/gem-lock

      - restore_cache:
          keys:
            - persistent_enum-<< parameters.ruby-version >>-{{ checksum "/tmp/gem-lock" }}
            - persistent_enum-

      - run:
          name: Bundle Install
          command: bundle check || bundle install

      - save_cache:
          key: persistent_enum-<< parameters.ruby-version >>-{{ checksum "/tmp/gem-lock" }}
          paths:
            - vendor/bundle

      - steps: << parameters.database-steps >>

      - run:
          name: Run rspec
          command: bundle exec rspec --profile 10 --format RspecJunitFormatter --out test_results/rspec.xml --format progress

      - store_test_results:
          path: test_results

  publish:
    executor: ruby-sqlite
    steps:
       - checkout
       - run:
           name: Setup Rubygems
           command: |
             mkdir ~/.gem &&
             echo -e "---\r\n:rubygems_api_key: $RUBYGEMS_API_KEY" > ~/.gem/credentials &&
             chmod 0600 ~/.gem/credentials
       - run:
           name: Publish to Rubygems
           command: |
             gem build persistent_enum.gemspec
             gem push persistent_enum-*.gem

workflows:
  version: 2
  build:
    jobs:
      - test:
          name: 'ruby 2.7 rails 5.2 sqlite'
          executor-name: ruby-sqlite
          ruby-version: "2.7"
          gemfile: gemfiles/rails_5_2.gemfile
      - test:
          name: 'ruby 3.0 rails 6.1 sqlite'
          executor-name: ruby-sqlite
          ruby-version: "3.0"
          gemfile: gemfiles/rails_6_1.gemfile
      - test:
          name: 'ruby 3.0 rails 7.0 sqlite'
          executor-name: ruby-sqlite
          ruby-version: "3.0"
          gemfile: gemfiles/rails_7_0.gemfile
      - test:
          name: 'ruby 2.7 rails 5.2 pg'
          executor-name: ruby-pg
          ruby-version: "2.7"
          gemfile: gemfiles/rails_5_2.gemfile
          database-steps: &pg_wait
            - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - test:
          name: 'ruby 3.0 rails 6.1 pg'
          executor-name: ruby-pg
          ruby-version: "3.0"
          gemfile: gemfiles/rails_6_1.gemfile
          database-steps: *pg_wait
      - test:
          name: 'ruby 3.0 rails 7.0 pg'
          executor-name: ruby-pg
          ruby-version: "3.0"
          gemfile: gemfiles/rails_7_0.gemfile
          database-steps: *pg_wait
      - test:
          name: 'ruby 2.7 rails 5.2 mysql'
          executor-name: ruby-mysql
          ruby-version: "2.7"
          gemfile: gemfiles/rails_5_2.gemfile
          database-steps: &mysql_wait
            - run: dockerize -wait tcp://localhost:3306 -timeout 1m
      - test:
          name: 'ruby 3.0 rails 6.1 mysql'
          executor-name: ruby-mysql
          ruby-version: "3.0"
          gemfile: gemfiles/rails_6_1.gemfile
          database-steps: *mysql_wait
      - test:
          name: 'ruby 3.0 rails 7.0 mysql'
          executor-name: ruby-mysql
          ruby-version: "3.0"
          gemfile: gemfiles/rails_7_0.gemfile
          database-steps: *mysql_wait
      - publish:
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
